apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: clientAddress
  description: Retrieve and manage client address details
  tags:
    - csharp
    - public
spec:
  type: openapi
  lifecycle: production
  owner: crm-team
  system: customer-management
  dependsOn:
    - api:default/client
  definition:
    $text: https://github.com/richardpitout/backstage-test/blob/main/services/clientaddress/swagger.yaml
